version: '3.9'

services:
  server:
      build: 
        context: ./server
        dockerfile: server.Dockerfile
      volumes: 
        - ./server:/usr/src/app
      links:
        - db
      ports:
        - "5000"

  db:
    build: 
      context: ./db
      dockerfile: db.Dockerfile
    ports:
      - "32000:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: movies_db
      MYSQL_ROOT_PASSWORD: root
    # command: ["--secure-file-priv=${PWD}"]
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - ./db:/app
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
    ports: 
      - 80:80
